# summary: Searchable texts of all AOPs (title and short name)
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?entity ?text ?kind
FROM <urn:aopwiki:graph>
WHERE {
  ?entity a aopo:AdverseOutcomePathway .
  { ?entity dc:title ?text . BIND("title" AS ?kind) }
  UNION { ?entity dcterms:alternative ?text . BIND("alias" AS ?kind) }
}
