# summary: grlc get-methods-for-aop: measurement methods of the Key Events of an AOP
# (fixed: accepts http:// or https:// AOP IRIs and bare ids)
# param: aop iri
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX mmo: <http://purl.obolibrary.org/obo/MMO_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?AopLabel ?KeLookUp ?AssayText
FROM <urn:aopwiki:graph>
WHERE {
  VALUES ?aop { ?__aop }
  ?KeLook a aopo:KeyEvent ;
    rdfs:label ?KeLookUp ;
    dcterms:isPartOf ?aop ;
    mmo:0000000 ?AssayText .
  ?aop rdfs:label ?AopLabel .
}
