# summary: grlc get-all-aos: all adverse outcomes (fixed: DISTINCT, one row per AO)
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?AO ?AOTitle ?AOID
FROM <urn:aopwiki:graph>
WHERE {
  ?AOP a aopo:AdverseOutcomePathway ;
    aopo:has_adverse_outcome ?AO .
  ?AO dc:title ?AOTitle ;
    rdfs:label ?AOID .
}
