# summary: grlc get-all-kes: all Key Events with title and label
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?KE ?KETitle ?KEID
FROM <urn:aopwiki:graph>
WHERE {
  ?KE a aopo:KeyEvent ;
    dc:title ?KETitle ;
    rdfs:label ?KEID .
}
